/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.gui;

import javax.swing.*;

/**
 *
 * @author bento
 */
public class frmDepositar extends javax.swing.JFrame {


	/**
	 * Creates new form frmDepositar
	 */
	public frmDepositar() {
		initComponents();
		setLocationRelativeTo(null);
	}

	public frmDepositar(Banco b, int numeroConta) {
		initComponents();
		setLocationRelativeTo(null);
		this.banco = b;
		this.numeroConta = numeroConta;
		this.cliente = banco.consultarNumero(numeroConta);
		tfConta.setText("00" + String.valueOf(cliente.getConta().getNumero()));
		tfSaldo.setText("R$ " + String.valueOf(cliente.getConta().getSaldo()));
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConta = new javax.swing.JLabel();
        tfConta = new javax.swing.JTextField();
        labelSaldo = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        btDepositar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConta.setText("Conta");

        tfConta.setEditable(false);
        tfConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfConta.setFocusable(false);

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSaldo.setText("Saldo");

        tfSaldo.setEditable(false);
        tfSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSaldo.setFocusable(false);
        tfSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSaldoActionPerformed(evt);
            }
        });

        labelValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValor.setText("Valor a depositar");

        tfValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btDepositar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDepositar.setText("Depositar");
        btDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositarActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDepositar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVoltar))
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelValor))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConta)
                    .addComponent(labelSaldo)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDepositar)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void btDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositarActionPerformed
		depositar();
        }//GEN-LAST:event_btDepositarActionPerformed

        private void tfSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSaldoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_tfSaldoActionPerformed

        private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
		voltar();
        }//GEN-LAST:event_btVoltarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmDepositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmDepositar().setVisible(true);
			}
		});
	}

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDepositar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
	private Banco banco;
	private int numeroConta;
	private Cliente cliente;
	
	private void voltar() {
		frmConta windowConta = new frmConta(banco, numeroConta);
		windowConta.setVisible(true);
		this.dispose();
	}
	
	private void depositar() {
			float valor = Float.parseFloat(tfValor.getText());
			int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo realizar o depósito?");
			if (op == 0){
				if (!banco.depositar(numeroConta, valor)) {
					JOptionPane.showMessageDialog(this, "Houve um erro ao realizar o depósito!");
				} else {
					JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso!");
					voltar();
				}
			} else if (op == 1){
				voltar();
		}
	}
}