/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.gui;

import javax.swing.*;

/**
 *
 * @author bento
 */
public class frmSacar extends javax.swing.JFrame {

    /**
     * Creates new form frmSacar
     */
    public frmSacar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public frmSacar(Banco b, int numeroConta) {
        initComponents();
	    setLocationRelativeTo(null);
	    this.banco = b;
        this.numeroConta = numeroConta;
        cliente = banco.consultarNumero(numeroConta);
	    tfSaldo.setText("R$ "+ String.valueOf(cliente.getConta().getSaldo()));
	    tfConta.setText("00" + String.valueOf(cliente.getConta().getNumero()));
    }

    /**
     * This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConta = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        labelSaldo = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        tfConta = new javax.swing.JTextField();
        btSacar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        tfSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saque");
        setResizable(false);

        labelConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelConta.setText("Conta");

        tfValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSaldo.setText("Saldo");

        labelValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValor.setText("Valor a sacar");

        tfConta.setEditable(false);
        tfConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfConta.setFocusable(false);

        btSacar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btSacar.setText("Sacar");
        btSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSacarActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        tfSaldo.setEditable(false);
        tfSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSaldo.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSacar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVoltar))
                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConta)
                    .addComponent(labelSaldo)
                    .addComponent(tfConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSacar)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSacarActionPerformed
	sacar();
    }//GEN-LAST:event_btSacarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSacar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSacar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField tfConta;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
    private Banco banco;
    private int numeroConta;
    private Cliente cliente;

    private void voltar() {
        frmConta windowConta = new frmConta(banco, numeroConta);
        windowConta.setVisible(true);
        this.dispose();
    }

    private void sacar() {
        float saldo = Float.parseFloat(tfValor.getText());
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo realizar o saque?");

        if (op == 0) {
            if (banco.sacar(numeroConta, saldo) == false) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente.");
            } else {
                JOptionPane.showMessageDialog(this, "Depósito realizado com sucesso!");
                voltar();
            }
        } else if (op == 1) {
            voltar();
        }
    }
}