/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco.gui;

import javax.swing.*;

/**
 *
 * @author bento
 * @author fredao
 * @author hugo
 * @author oi :D
 */
public class frmTransferir extends javax.swing.JFrame {

	/**
	 * Creates new form frmTransferir
	 */
	public frmTransferir() {
		initComponents();
	}

	public frmTransferir(Banco b, int numeroConta) {
		initComponents();
		setLocationRelativeTo(null);
		this.banco = b;
		this.numeroConta = numeroConta;
		this.cliente = banco.consultarNumero(numeroConta);

		if (this.numeroConta < 10) {
			tfOrigem.setText("00" + String.valueOf(this.numeroConta));
		} else if (this.numeroConta < 100) {
			tfOrigem.setText("0" + String.valueOf(this.numeroConta));
		} else {
			tfOrigem.setText(String.valueOf(this.numeroConta));
		}

		tfTipoConta.setText(cliente.getConta().getTipo());
		tfNomeOrigem.setText(cliente.getNome());
		tfSaldo.setText("R$ " + String.valueOf(cliente.getConta().getSaldo()));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSaldo = new javax.swing.JLabel();
        labelOrigem = new javax.swing.JLabel();
        labelTipoContaDestino = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelTipoContaOrigem = new javax.swing.JLabel();
        tfTipoConta = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        tfOrigem = new javax.swing.JTextField();
        tfNomeDestino = new javax.swing.JTextField();
        tfNomeOrigem = new javax.swing.JTextField();
        tfDestinoConta = new javax.swing.JTextField();
        tfSaldo = new javax.swing.JTextField();
        btTransferir = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        cbTipoConta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transferência");
        setResizable(false);

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSaldo.setText("Saldo");

        labelOrigem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelOrigem.setText("Origem");

        labelTipoContaDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipoContaDestino.setText("Tipo da Conta de Destino");

        labelDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDestino.setText("Destino");

        labelValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValor.setText("Valor a transferir");

        labelNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNome.setText("Nome");

        labelTipoContaOrigem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipoContaOrigem.setText("Tipo da Conta");

        tfTipoConta.setEditable(false);
        tfTipoConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTipoConta.setFocusable(false);

        tfValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tfOrigem.setEditable(false);
        tfOrigem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfOrigem.setFocusable(false);

        tfNomeDestino.setEditable(false);
        tfNomeDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNomeDestino.setFocusable(false);

        tfNomeOrigem.setEditable(false);
        tfNomeOrigem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNomeOrigem.setFocusable(false);

        tfDestinoConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfDestinoConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDestinoContaFocusLost(evt);
            }
        });

        tfSaldo.setEditable(false);
        tfSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSaldo.setFocusable(false);

        btTransferir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTransferir.setText("Transferir");
        btTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferirActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        cbTipoConta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corrente", "Poupança" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btTransferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVoltar))
                    .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoContaDestino)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfNomeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelOrigem)
                                .addGap(18, 18, 18)
                                .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTipoContaOrigem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(tfNomeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDestino)
                        .addGap(18, 18, 18)
                        .addComponent(tfDestinoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSaldo)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrigem)
                    .addComponent(tfOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipoContaOrigem)
                    .addComponent(tfTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDestino)
                    .addComponent(tfDestinoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTipoContaDestino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTransferir)
                    .addComponent(btVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
			voltar();
        }//GEN-LAST:event_btVoltarActionPerformed

    private void tfDestinoContaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDestinoContaFocusLost
		consultar();
    }//GEN-LAST:event_tfDestinoContaFocusLost

    private void btTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferirActionPerformed
		transferir();
    }//GEN-LAST:event_btTransferirActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmTransferir().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTransferir;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbTipoConta;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelOrigem;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTipoContaDestino;
    private javax.swing.JLabel labelTipoContaOrigem;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField tfDestinoConta;
    private javax.swing.JTextField tfNomeDestino;
    private javax.swing.JTextField tfNomeOrigem;
    private javax.swing.JTextField tfOrigem;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfTipoConta;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
	private Banco banco;
	private Cliente cliente, clienteDestino;
	private int numeroConta;

	private void voltar() {
		frmConta windowConta = new frmConta(banco, numeroConta);
		windowConta.setVisible(true);
		this.dispose();
	}

	private void consultar() {

		if (tfDestinoConta.getText().equals("")) {
			tfNomeDestino.setText("");
		} else {
			clienteDestino = banco.consultarNumero(Integer.parseInt(tfDestinoConta.getText()));

			if (clienteDestino == null) {
				JOptionPane.showMessageDialog(this, "Número da conta inválido!");
				tfDestinoConta.setText("");
			} else {
				tfNomeDestino.setText(clienteDestino.getNome());
			}
		}
	}

	private void transferir() {
		if (tfDestinoConta.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Você deve informar uma conta de destino!");
		} else if (tfValor.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "Você deve informar valor!");
		} else if (tfDestinoConta.getText().equals(tfOrigem.getText())){
			JOptionPane.showMessageDialog(this, "Conta de origem não pode igual à de destino!");
			tfDestinoConta.setText("");
			tfValor.setText("");
			tfNomeDestino.setText("");
		} else {
			clienteDestino = banco.consultarNumero(Integer.parseInt(tfDestinoConta.getText()));

			if (banco.transferir(cliente.getConta().getNumero(), clienteDestino.getConta().getNumero(), Integer.parseInt(tfValor.getText()))){
				JOptionPane.showMessageDialog(this, "Transferência realizada com sucesso!");
				voltar();
			} else {
				JOptionPane.showMessageDialog(this, "Erro ao realizar a transferência!");
				tfDestinoConta.setText("");
				tfValor.setText("");
				tfNomeDestino.setText("");
			}
		}
	}
}
